### PR TITLE
Testing ModelImporter

### PR DESCRIPTION
**Pull request by niccojacinto**
Need a clear direction on the framework for further implementation.

### CODE REVIEW

**Comment by kyatohon** [comment]
ModelManager structure is odd.
It has a lot of static methods - is there a point of instantiating a ModelManager instance? It might be better to make it a singleton OR make it a purely static class.

**Comment by kyatohon** [comment]
ModelManager::LoadModel
It looks logically correct. But what's with the spacing? There's a vortex between the if and else statement.

**Comment by kyatohon** [comment]
ModelManager include order: Debug and Macro (Our Project Files) should be included last. Please refer to the Wiki.

**Comment by kyatohon** [comment]
Use the Copy Constructor Macro instead of manually typing the copy constructor delete stuff out.

**Comment by kyatohon** [comment]
It would be great if the Model and GameObject instantiation happened in TestScene::Initialize().  🗡 😄

**Comment by kyatohon** [comment]
Ideally, Model_view matrix should be obtained from GameObject::Transform. Hook up with @hau5tastic for full details.

**Comment by kyatohon** [comment]
Include order in SuGameObject.h does not adhere to our standards. 🏩

**Comment by kyatohon** [comment]
SuGameObject.h has space vortex issues.

**Comment by kyatohon** [comment]
There are a lot of assets in here though; perhaps we should use an alternate file host for them.

**Comment by kyatohon** [comment]
Overall, it's quite interesting. It's too bad that ModelImporter does not absorb the correct vertices yet.

Scott recommended to use .obj, as it is a simpler format to conform to, and can reduce the variances encountered with .FBX. He also recommended to just open the .FBX files in 3DS Studio, and export them as .obj with our settings desired (Such as redundant vertices).

**Comment by kyatohon** [comment]
Scene Importing: aiProcess_JoinIdenticalVertices flag is set to true, but it's not the behavior we want - it should be omitted.

**Comment by kyatohon** [comment]
Issue #34 
I'm having inconsistencies in the behavior of our current AiScene reader. Did a mistake happen along the way? Is the GPU Corrupted? I think it's time to make a change.

**Comment by hau5tastic** [comment]
modelid is public and not following the order of our coding conventions

**Comment by hau5tastic** [comment]
testing is also done in game engine and not test proj :-1:

**Comment by hau5tastic** [comment]
otherwise looks good

**Comment by kyatohon** [comment]
what the f**k is this

**Comment by kyatohon** [comment]
Caught @hau5tastic  sneaking in commits without review

**Pull request merged**
